# This is a dynamic yml configuration file
# It defines the repository structure for various Working Groups
# For documentation, refer to the README in this directory

## Front and end matter

front-matter:
- https://raw.githubusercontent.com/chaoss/website/master/release/chaoss-contributor-list.md

end-matter:
- https://raw.githubusercontent.com/chaoss/website/master/release/release-notes.md
- https://raw.githubusercontent.com/chaoss/website/master/LICENSE

## Working Groups

# WG-Common

wg-common:
  include-wg: True
  wg-fullname: Common Metrics WG
  github-link: None
  github-branch: None
  focus-areas:
    what:
    - technical-fork.md
    - types-of-contributions.md
    when:
    - activity-dates-and-times.md
    - burstiness.md
    - review-cycle-duration-within-a-change-request.md
    - time-to-close.md
    - time-to-first-response.md
    where:
    who:
    - contributor-location.md
    - contributors.md
    - organizational-diversity.md


# WG-DEI

wg-diversity-inclusion:
  include-wg: False
  wg-fullname: Diversity, Equity and Inclusion WG
  github-link: None
  github-branch: None
  focus-areas:
#    communication-inclusivity:
#    - alternatives.md
#    - captioning.md
#    - listening.md
#    - mode-alternatives.md
#    - speaking.md
#    - technical-jargon.md
#    contributor-community-diversity:
#    - collaboration-style.md
#    - contribution-sentiment.md
#    - contribution-type.md
#    - perceived-value.md
    event-diversity:
    - attendee-demographics.md
    - diversity-access-tickets.md
    - event-code-of-conduct.md
    - family-friendly.md
#    - quick-links.md
    - speaker-demographics.md
    governance:
    - board-council-diversity.md
#    - code-of-conduct-enforcement.md
    - code-of-conduct.md
#    - foundation-staff-diversity.md
#    - team-module-ownership-diversity.md
    leadership:
    - inclusive-leadership.md
    - mentorship.md
    - sponsorship.md
    project-and-community:
#    - channels.md
    - chat-platform-inclusivity.md
    - documentation-accessibility.md
#    - documentation_discoverability.md
    - documentation-usability.md
    - issue-label-inclusivity.md
    - project-burnout.md
#    - response-time-quality.md
#    - sentiment.md
#    recognition-of-good-work:
#    - contribution-type.md
#    - contribution-volume.md
#    - recognition-type.md
#    - recognition-value.md

# WG-Evolution

wg-evolution:
  include-wg: False
  wg-fullname: Evolution WG
  github-link: None
  github-branch: None
  focus-areas:
    code-development-activity:
    - branch-lifecycle.md
    - code-changes-lines.md
    - code-changes.md
    code-development-efficiency:
    - change-request-acceptance-ratio.md
    - change-requests-accepted.md
    - change-requests-declined.md
    - change-requests-duration.md
    code-development-process-quality:
    - change-requests.md
    community-growth:
    - contribution-attribution.md
    - inactive-contributors.md
    - new-contributor-closing-issues.md
    - new-contributors.md
    issue-resolution:
    - issue-age.md
    - issue-resolution-duration.md
    - issue-response-time.md
    - issues-active.md
    - issues-closed.md
    - issues-new.md


# WG-Risk

wg-risk:
  include-wg: False
  wg-fullname: Risk WG
  github-link: None
  github-branch: None
  focus-areas:
    business-risk:
#    - average-issue-resolution-time.md
    - bus-factor.md
    - committers.md
    - elephant-factor.md
#    - issues-open-age.md
#    - issues-volume.md
#    - lines-of-code.md
    code-quality:
#    - code-complexity.md
#    - pull-request-process.md
    - test-coverage.md
    licensing:
#    - license-count.md
    - license-coverage.md
    - license-declared.md
    - osi-approved-licenses.md
    - spdx-document.md
    security:
    - cii-best-practices.md
#    - language-declaration-readme.md
#    - language-source-proportion.md
    transparency:
#    - software-bill-of-materials.md


# WG-Value

wg-value:
  include-wg: True
  wg-fullname: Value WG
  github-link: None
  github-branch: None
  focus-areas:
    communal-value:
#    - project-popularity.md
    - project-velocity.md
#    - social-listening.md
    individual-value:
    - job-opportunities.md
    - organizational-project-skill-demand.md
    organizational-value:
    - labor-investment.md
    social-value:


