# This is a dynamic yml configuration file
# It defines the repository structure for various Working Groups
# It serves as the only input for the automation process
# For documentation, refer to the README in this directory


# WG-COMMON

wg-common:
  include-wg: True
  wg-fullname: Common Metrics WG
  github-link: https://github.com/chaoss/wg-common
  github-branch: master
  focus-areas:
    what:
    - technical-fork.md
    - types-of-contributions.md
    when:
    - activity-dates-and-times.md
    - burstiness.md
    - review-cycle-duration-within-a-change-request.md
    - time-to-close.md
    - time-to-first-response.md
    where:
    who:
    - contributor-location.md
    - contributors.md
    - organizational-diversity.md


# WG-VALUE

wg-value:
  include-wg: True
  wg-fullname: Value WG
  github-link: https://github.com/ritik-malik/wg-value
  github-branch: master
  focus-areas:
    communal-value:
    - project-popularity.md
    - project-velocity.md
    - social-listening.md
    individual-value:
    - job-opportunities.md
    - organizational-project-skill-demand.md
    organizational-value:
    - labor-investment.md
    social-value:
    
# WG-EVOLUTION

wg-evolution:
  include-wg: False
  wg-fullname: Evolution WG
  github-link: https://github.com/chaoss/wg-evolution
  github-branch: master
  focus-areas:
    code-development-activity:
    - branch-lifecycle.md
    - code-changes-lines.md
    - code-changes.md
    code-development-efficiency:
    - change-request-acceptance-ratio.md
    - change-requests-accepted.md
    - change-requests-declined.md
    - change-requests-duration.md
    code-development-process-quality:
    - change-requests.md
    community-growth:
    - contribution-attribution.md
    - inactive-contributors.md
    - new-contributor-closing-issues.md
    - new-contributors.md
    issue-resolution:
    - issue-age.md
    - issue-resolution-duration.md
    - issue-response-time.md
    - issues-active.md
    - issues-closed.md
    - issues-new.md

