# This is a dynamic yml configuration file
# It defines the repository structure for various Working Groups
# For documentation, refer to the README in this directory

## Front and end matter

front-matter:

end-matter:
- https://raw.githubusercontent.com/chaoss/website/master/release/latest-release-notes.md
- https://raw.githubusercontent.com/chaoss/website/master/release/chaoss-contributor-list.md
- https://raw.githubusercontent.com/chaoss/website/master/LICENSE

## Working Groups

# WG-Common

wg-common:
  include-wg: True
  wg-fullname: Common Metrics WG
  repo-link: https://github.com/chaoss/wg-common
  repo-branch: main
  focus-areas-location: wg-common/focus-areas
  focus-areas:
    contributions:
    - clones.md
    - occassional-contributors.md
    - programming-language-distribution.md
    - technical-fork.md
    - types-of-contributions.md
    time:
    - activity-dates-and-times.md
    - burstiness.md
    - review-cycle-duration-within-a-change-request.md
    - time-to-first-response.md
    - time-to-close.md
    people:
    - bot-activity.md
    - contributors.md
    - contributor-location.md
    - organizational-diversity.md
    place:
    - collaboration-platform-activity.md
    - event-locations.md


# WG-DEI

wg-dei:
  include-wg: True
  wg-fullname: Diversity, Equity and Inclusion WG
  repo-link: https://github.com/chaoss/wg-dei
  repo-branch: main
  focus-areas-location: wg-dei/focus-areas
  focus-areas:

    event-diversity:
    - event-code-of-conduct.md
    - diversity-access-tickets.md
    - event-accessibility.md
    - event-demographics.md
    - family-friendly.md
    - inclusive-experience.md
    - time-inclusion.md
    governance:
    - board-council-diversity.md
    - code-of-conduct.md

    leadership:
    - inclusive-leadership.md
    - mentorship.md
    - sponsorship.md
    project-and-community:
    - chat-platform-inclusivity.md
    - documentation-accessibility.md
    - documentation-discoverability.md
    - documentation-usability.md
    - issue-label-inclusivity.md
    - project-burnout.md
    - project-demographics.md
    - psychological-safety.md

# WG-Evolution

wg-evolution:
  include-wg: True
  wg-fullname: Evolution WG
  repo-link: https://github.com/chaoss/wg-evolution
  repo-branch: main
  focus-areas-location: wg-evolution/focus-areas
  focus-areas:
    code-development-activity:
    - branch-lifecycle.md
    - change-request-commits.md
    - code-changes-commits.md
    - code-changes-lines.md
    code-development-efficiency:
    - change-requests-accepted.md
    - change-requests-declined.md
    - change-requests-duration.md
    - change-request-acceptance-ratio.md
    code-development-process-quality:
    - change-requests.md
    - change-request-reviews.md
    issue-resolution:
    - issues-new.md
    - issues-active.md
    - issues-closed.md
    - issue-age.md
    - issue-response-time.md
    - issue-resolution-duration.md
    community-growth:
    - contribution-attribution.md
    - inactive-contributors.md
    - new-contributors.md
    - new-contributor-closing-issues.md


# WG-Risk

wg-risk:
  include-wg: True
  wg-fullname: Risk WG
  repo-link: https://github.com/chaoss/wg-risk
  repo-branch: main
  focus-areas-location: wg-risk/focus-areas
  focus-areas:
    business-risk:
#    - average-issue-resolution-time.md
    - bus-factor.md
    - committers.md
    - elephant-factor.md

    code-quality:
    - defect-resolution-time.md
    - test-coverage.md
    dependency-risk-assessment:
    - libyear.md
    - upstream-code-dependencies.md
    licensing:
    - license-coverage.md
    - license-declared.md
    - osi-approved-licenses.md
    - spdx-document.md
    security:
    - openssf-best-practices.md


# WG-Value

wg-value:
  include-wg: True
  wg-fullname: Value WG
  repo-link: https://github.com/chaoss/wg-value
  repo-branch: main
  focus-areas-location: wg-value/focus-areas
  focus-areas:
    academic-value:
    - academic-open-source-project-impact.md
    communal-value:
    - project-recommendability.md
    - project-velocity.md
    individual-value:
    - organizational-project-skill-demand.md
    - job-opportunities.md
    organizational-value:
    - organizational-influence.md
    - labor-investment.md
